### ISSUE TITLE
Error while running sample profile.

### ISSUE THREAD

**Issue by paoloantinori** [fabric8io/fabric8-forge#487]
```
✘-INT /data/repositories/github/fuse/fabric8-forge/fabric8-forge-core [master|✔] 
11:13 $ mvn clean install -Psample exec:java
```

```
INFO: WELD-ENV-002003: Weld SE container org.jboss.forge.addon:javaee initialized
Connecting to service gogs on : from $GOGS_SERVICE_HOST and $GOGS_SERVICE_PORT
FAILED o.e.j.s.ServletContextHandler@7b35bcee{/,null,STARTING}: org.jboss.weld.exceptions.DeploymentException: Exception List with 1 exceptions:
Exception 0 :
java.lang.IllegalArgumentException: No kubernetes service could be found for name: gogs in namespace: null
    at io.fabric8.kubernetes.api.KubernetesHelper.getServiceURL(KubernetesHelper.java:1324)
    at io.fabric8.cdi.Services.toServiceUrl(Services.java:38)
    at io.fabric8.cdi.producers.ServiceUrlProducer.produce(ServiceUrlProducer.java:47)
    at io.fabric8.cdi.producers.ServiceUrlProducer.produce(ServiceUrlProducer.java:26)
    at io.fabric8.cdi.bean.ProducerBean.create(ProducerBean.java:43)
    at org.jboss.weld.context.unbound.DependentContextImpl.get(DependentContextImpl.java:70)
    at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:101)
```

**Comment by davsclaus** [comment]
You need to have a running fabric8 on kubernetes with ci/cd pipeline that has gogs/jenkins etc.
