### ISSUE TITLE
pipeline <h3>Caused by:</h3><pre>java.net.UnknownHostException: gogs.default.vagrant.f8 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)

### ISSUE THREAD

**Issue by RobinsChens** [fabric8io/fabric8-forge#593]
libs.js:120934[Forge] Failed to load http://fabric8.default.vagrant.f8/k8s/api/v1/proxy/namespaces/default/servi…s-https-admin&secretNamespace=user-secrets-source-admin&kubeUserName=admin <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 500 Server Error</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /api/forge/command/execute/devops-get-overview. Reason:
<pre>    Server Error</pre></p><h3>Caused by:</h3><pre>java.lang.RuntimeException: Failed to command remote repo http://gogs.default.vagrant.f8/gogsadmin/jenkins.git due: http://gogs.default.vagrant.f8/gogsadmin/jenkins.git: cannot open git-upload-pack
    at io.fabric8.forge.rest.main.ProjectFileSystem.cloneRepo(ProjectFileSystem.java:209)
    at io.fabric8.forge.rest.main.ProjectFileSystem.cloneRepoIfNotExist(ProjectFileSystem.java:190)
    at io.fabric8.forge.rest.git.RepositoryResource$15.call(RepositoryResource.java:757)
    at io.fabric8.forge.rest.git.GitLockManager.withLock(GitLockManager.java:45)
    at io.fabric8.forge.rest.git.RepositoryResource.gitOperation(RepositoryResource.java:753)
    at io.fabric8.forge.rest.git.RepositoryResource.gitWriteoperation(RepositoryResource.java:749)
    at io.fabric8.forge.rest.git.RepositoryResource.gitWriteOperation(RepositoryResource.java:743)
    at io.fabric8.forge.rest.CommandsResource.withUIContext(CommandsResource.java:651)
    at io.fabric8.forge.rest.CommandsResource.withUIContext(CommandsResource.java:619)
    at io.fabric8.forge.rest.CommandsResource.executeCommand(CommandsResource.java:333)
    at sun.reflect.GeneratedMethodAccessor645.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:180)
    at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
    at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:189)
    at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99)
    at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
    at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
    at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
    at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
    at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:254)

**Comment by davsclaus** [comment]
We recommend NOT to use vagrant anymore. Its much better to use minikube or minishift. You can find details in the getting started guide at: https://fabric8.io/guide/getStarted/index.html
