### ISSUE TITLE
unable to create vertx project 

### ISSUE THREAD

**Issue by kameshsampath** [fabric8io/fabric8-forge#693]
Unable to create new project of type "vertx" via fabric8 console, the creation results in archetype not found 

```
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find io.fabric8.archetypes:vertx-simplest-archetype:jar:2.2.181 in http://repo1.maven.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:231)
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:585)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:503)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	... 82 more

```

**Comment by davsclaus** [comment]
Yeah we are moving to vertx-web as the archetype. This change requires a number of other repos to be released and version upgraded to make that transition.

Maybe you can try again with latest releases?

**Comment by kameshsampath** [comment]
@davsclaus i just updated to latest gofabric8 and tried creating vert.x app.. still getting same issue as above.. is that anything I need to do additional other than updating gofabric8? will try creating a new minishift env

**Comment by davsclaus** [comment]
Ah yeah a new release of fabric8-archetypes is needed that includes vertx-web and a new forge release as well that uses this archetype

**Comment by davsclaus** [comment]
The archetypes has been updated, so when there is a new release of fabric8-forge it ought to use that for vertx.

**Comment by kameshsampath** [comment]
thanks @davsclaus

**Comment by davsclaus** [comment]
It works now in the latest release
