### ISSUE TITLE
new NodeJS app fails:  A project is required in the current context

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8-forge#752]
reported from IRC

when chosing to build a new NodeJS application in the fabric8 UI no pipelines are presented.  In the fabric8-forge logs we see the error:

```
HTTP ERROR 500
Problem accessing /api/forge/command/execute/devops-edit. Reason:

    Server Error
Caused by:

java.lang.IllegalStateException: Error while moving to the next wizard step
	at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.refreshFlow(WizardCommandControllerImpl.java:107)
	at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.canExecute(WizardCommandControllerImpl.java:319)
	at org.jboss.forge.addon.ui.impl.controller.NoUIWizardControllerDecorator.canExecute(NoUIWizardControllerDecorator.java:230)
	at sun.reflect.GeneratedMethodAccessor460.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback$2.call(ClassLoaderAdapterCallback.java:124)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback.invoke(ClassLoaderAdapterCallback.java:97)
	at org.jboss.forge.addon.ui.controller.CommandController_$$_javassist_a67eebf2-506d-47b6-bb57-9e58fa779b81.canExecute(CommandController_$$_javassist_a67eebf2-506d-47b6-bb57-9e58fa779b81.java)
	at io.fabric8.forge.rest.dto.UICommands.createValidationResult(UICommands.java:358)
	at io.fabric8.forge.rest.CommandsResource.doExecute(CommandsResource.java:394)
	at io.fabric8.forge.rest.CommandsResource$4.apply(CommandsResource.java:349)
	at io.fabric8.forge.rest.CommandsResource$4.apply(CommandsResource.java:345)
	at io.fabric8.forge.rest.CommandsResource$6.call(CommandsResource.java:655)
	at io.fabric8.forge.rest.git.RepositoryResource$15.call(RepositoryResource.java:803)
	at io.fabric8.forge.rest.git.GitLockManager.withLock(GitLockManager.java:45)
	at io.fabric8.forge.rest.git.RepositoryResource.gitOperation(RepositoryResource.java:754)
	at io.fabric8.forge.rest.git.RepositoryResource.gitWriteOperation(RepositoryResource.java:750)
	at io.fabric8.forge.rest.git.RepositoryResource.gitWriteOperation(RepositoryResource.java:744)
	at io.fabric8.forge.rest.CommandsResource.withUIContext(CommandsResource.java:665)
	at io.fabric8.forge.rest.CommandsResource.withUIContext(CommandsResource.java:633)
	at io.fabric8.forge.rest.CommandsResource.executeCommand(CommandsResource.java:345)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:180)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:189)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:254)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:180)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:298)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:273)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:837)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:524)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)



Caused by: java.lang.IllegalStateException: A project is required in the current context
	at org.jboss.forge.addon.projects.ui.AbstractProjectCommand.getSelectedProject(AbstractProjectCommand.java:86)
	at io.fabric8.forge.devops.setup.Fabric8SetupStep.initializeUI(Fabric8SetupStep.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
	at io.fabric8.forge.devops.setup.Fabric8SetupStep_$$_javassist_74ee5d2e-d15f-48e0-9ddb-989a3a36b817.initializeUI(Fabric8SetupStep_$$_javassist_74ee5d2e-d15f-48e0-9ddb-989a3a36b817.java)
	at org.jboss.forge.addon.ui.impl.controller.SingleCommandControllerImpl.initialize(SingleCommandControllerImpl.java:61)
	at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.next(WizardCommandControllerImpl.java:391)
	at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.refreshFlow(WizardCommandControllerImpl.java:103)
	at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.canExecute(WizardCommandControllerImpl.java:319)
	at org.jboss.forge.addon.ui.impl.controller.NoUIWizardControllerDecorator.canExecute(NoUIWizardControllerDecorator.java:230)
	at sun.reflect.GeneratedMethodAccessor460.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback$2.call(ClassLoaderAdapterCallback.java:124)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback.invoke(ClassLoaderAdapterCallback.java:97)
	at org.jboss.forge.addon.ui.controller.CommandController_$$_javassist_a67eebf2-506d-47b6-bb57-9e58fa779b81.canExecute(CommandController_$$_javassist_a67eebf2-506d-47b6-bb57-9e58fa779b81.java)
	at io.fabric8.forge.rest.dto.UICommands.createValidationResult(UICommands.java:358)
	at io.fabric8.forge.rest.CommandsResource.doExecute(CommandsResource.java:394)
	at io.fabric8.forge.rest.CommandsResource$4.apply(CommandsResource.java:349)
	at io.fabric8.forge.rest.CommandsResource$4.apply(CommandsResource.java:345)
	at io.fabric8.forge.rest.CommandsResource$6.call(CommandsResource.java:655)
	at io.fabric8.forge.rest.git.RepositoryResource$15.call(RepositoryResource.java:803)
	at io.fabric8.forge.rest.git.GitLockManager.withLock(GitLockManager.java:45)
	at io.fabric8.forge.rest.git.RepositoryResource.gitOperation(RepositoryResource.java:754)
	at io.fabric8.forge.rest.git.RepositoryResource.gitWriteOperation(RepositoryResource.java:750)
	at io.fabric8.forge.rest.git.RepositoryResource.gitWriteOperation(RepositoryResource.java:744)
	at io.fabric8.forge.rest.CommandsResource.withUIContext(CommandsResource.java:665)
	at io.fabric8.forge.rest.CommandsResource.withUIContext(CommandsResource.java:633)
	at io.fabric8.forge.rest.CommandsResource.executeCommand(CommandsResource.java:345)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:180)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:189)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:254)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:180)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:298)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:273)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:837)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:524)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by rawlingsj** [comment]
A work around till a fix is available is to first select a new Microservice app and go as far as the select pipelines screen.  This looks like it will get the Jenkinsfiles.  

You can then go back and create a NodeJS app and have the pipelines displayed.

**Comment by davsclaus** [comment]
Thanks I think its trying to detect that fabric8-setup is needed to make it fabricated project.

Because its from the project-new it ought to work ootb for fabric8. So let me see if we need to add a check in that wizard to skip that fabric8-setup step

**Comment by davsclaus** [comment]
Your node should work in next release
