### ISSUE TITLE
When fabric8-console create new project, fabric8-forge throws "contains unmerged paths" and "HEAD is detached"

### ISSUE THREAD

**Issue by lastboy1228** [fabric8io/fabric8-forge#842]
But it  truely downloaded Jenkinsfile from fabric8-jenkinsfile-library and checked in local gogs repo.
```
2017-05-26T13:25:07.828696617Z Stashing local changes to the repo
2017-05-26T13:25:07.833036317Z Failed to stash changes: org.eclipse.jgit.api.errors.UnmergedPathsException: Repository contains unmerged paths
2017-05-26T13:25:07.833066816Z org.eclipse.jgit.api.errors.UnmergedPathsException: Repository contains unmerged paths
2017-05-26T13:25:07.833072416Z 	at org.eclipse.jgit.api.StashCreateCommand.call(StashCreateCommand.java:279)[org.eclipse.jgit-4.6.0.201612231935-r.jar:4.6.0.201612231935-r]
2017-05-26T13:25:07.833077416Z 	at io.fabric8.forge.rest.main.ProjectFileSystem.doPull(ProjectFileSystem.java:269)[fabric8-forge-core-2.3.90.jar:2.3.90]
2017-05-26T13:25:07.833081816Z 	at io.fabric8.forge.rest.main.ProjectFileSystem.cloneOrPullRepo(ProjectFileSystem.java:188)[fabric8-forge-core-2.3.90.jar:2.3.90]
2017-05-26T13:25:07.833086016Z 	at io.fabric8.forge.rest.main.ProjectFileSystem$1.run(ProjectFileSystem.java:141)[fabric8-forge-core-2.3.90.jar:2.3.90]
2017-05-26T13:25:07.833090216Z 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_111]
2017-05-26T13:25:07.833094316Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_111]
2017-05-26T13:25:07.833098316Z 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_111]
2017-05-26T13:25:07.833102316Z 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_111]
2017-05-26T13:25:07.833127015Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_111]
2017-05-26T13:25:07.833131815Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_111]
2017-05-26T13:25:07.833136015Z 	at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]
2017-05-26T13:25:07.833140115Z Cause: org.eclipse.jgit.errors.UnmergedPathException: Unmerged path: django/CanaryReleaseStage/Jenkinsfile
2017-05-26T13:25:07.833144315Z org.eclipse.jgit.errors.UnmergedPathException: Unmerged path: django/CanaryReleaseStage/Jenkinsfile
2017-05-26T13:25:07.833148215Z 	at org.eclipse.jgit.api.StashCreateCommand.call(StashCreateCommand.java:279)[org.eclipse.jgit-4.6.0.201612231935-r.jar:4.6.0.201612231935-r]
2017-05-26T13:25:07.833152414Z 	at io.fabric8.forge.rest.main.ProjectFileSystem.doPull(ProjectFileSystem.java:269)[fabric8-forge-core-2.3.90.jar:2.3.90]
2017-05-26T13:25:07.833156614Z 	at io.fabric8.forge.rest.main.ProjectFileSystem.cloneOrPullRepo(ProjectFileSystem.java:188)[fabric8-forge-core-2.3.90.jar:2.3.90]
2017-05-26T13:25:07.833225513Z 	at io.fabric8.forge.rest.main.ProjectFileSystem$1.run(ProjectFileSystem.java:141)[fabric8-forge-core-2.3.90.jar:2.3.90]
2017-05-26T13:25:07.833235213Z 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_111]
2017-05-26T13:25:07.833239512Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_111]
2017-05-26T13:25:07.833251812Z 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_111]
2017-05-26T13:25:07.833257012Z 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_111]
2017-05-26T13:25:07.833261312Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_111]
2017-05-26T13:25:07.833265512Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_111]
2017-05-26T13:25:07.833269412Z 	at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]
```

**Comment by lastboy1228** [comment]
```
2017-05-26T13:25:07.833273312Z Performing a pull in git repository /tmp/fabric8-forge/jenkinsfiles/.git on remote URL: https://github.com/fabric8io/fabric8-jenkinsfile-library.git
2017-05-26T13:25:07.833277412Z Using UsernamePasswordCredentialsProvider{user: lastboy1228, password length: 0}
2017-05-26T13:25:07.833281412Z Failed to pull from the remote git repo with credentials UsernamePasswordCredentialsProvider{user: lastboy1228, password length: 0} due: HEAD is detached. This exception is ignored.
2017-05-26T13:25:07.833285611Z org.eclipse.jgit.api.errors.DetachedHeadException: HEAD is detached
2017-05-26T13:25:07.833289411Z 	at org.eclipse.jgit.api.PullCommand.call(PullCommand.java:215)[org.eclipse.jgit-4.6.0.201612231935-r.jar:4.6.0.201612231935-r]
2017-05-26T13:25:07.833293511Z 	at io.fabric8.forge.rest.main.ProjectFileSystem.doPull(ProjectFileSystem.java:285)[fabric8-forge-core-2.3.90.jar:2.3.90]
2017-05-26T13:25:07.833297511Z 	at io.fabric8.forge.rest.main.ProjectFileSystem.cloneOrPullRepo(ProjectFileSystem.java:188)[fabric8-forge-core-2.3.90.jar:2.3.90]
2017-05-26T13:25:07.833308911Z 	at io.fabric8.forge.rest.main.ProjectFileSystem$1.run(ProjectFileSystem.java:141)[fabric8-forge-core-2.3.90.jar:2.3.90]
2017-05-26T13:25:07.833313511Z 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_111]
2017-05-26T13:25:07.833317611Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_111]
2017-05-26T13:25:07.833321511Z 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_111]
2017-05-26T13:25:07.833326710Z 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_111]
2017-05-26T13:25:07.833331210Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_111]
2017-05-26T13:25:07.833335110Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_111]
2017-05-26T13:25:07.833339010Z 	at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]
2017-05-26T13:25:07.833342710Z doPull took 5
2017-05-26T13:25:07.833346310Z asyncCloneOrPullJenkinsWorkflows took 5
```
